### PR TITLE
Add ScreeningPhaseStability notebook

### PR DESCRIPTION
**Pull request by bocklund**
[Rendered notebook view](https://nbviewer.jupyter.org/github/pycalphad/cookbook/blob/4ad1b7a31add5885a554d24dcaf0fadef694c7e5/ScreeningPhaseStability/ScreeningPhaseStability.ipynb)

### CODE REVIEW

**Comment by bocklund** [comment]
New version incoming that uses all `xarray` instead of dropping into `numpy`:

```python
# Index into the result to find all points where FCC and HCP are stable
import numpy as np
dims_list = list(eq_result.dims)

# We need to handle both potential orderings of the phases
masked_idxs = np.nonzero(np.sum(eq_result.Phase.values == ['FCC_A1', 'HCP_A3', ''], axis=-1) == 3)
T_idxs = masked_idxs[dims_list.index('T')]
X_ZN_idxs = masked_idxs[dims_list.index('X_ZN')]
plt.scatter(eq_result.X_ZN[X_ZN_idxs], eq_result.T[T_idxs], c='teal', s=2)

masked_idxs = np.nonzero(np.sum(eq_result.Phase.values == ['HCP_A3', 'FCC_A1', ''], axis=-1) == 3)
T_idxs = masked_idxs[dims_list.index('T')]
X_ZN_idxs = masked_idxs[dims_list.index('X_ZN')]
plt.scatter(eq_result.X_ZN[X_ZN_idxs], eq_result.T[T_idxs], c='teal', s=2)
```

is now 

```python
mask_cond = (eq_result.Phase.isin('FCC_A1').sum(dim='vertex') == 1) & (eq_result.Phase.isin('HCP_A3').sum(dim='vertex') == 1)
X_ZN = eq_result.X_ZN.where(mask_cond).transpose(*mask_cond.dims)
T = eq_result.T.where(mask_cond).transpose(*mask_cond.dims)
plt.scatter(X_ZN, T, c='teal', s=2)
```

**Comment by bocklund** [comment]
New rendered view: https://nbviewer.jupyter.org/github/pycalphad/cookbook/blob/0611a193fb111ddde4dd3c1b5c07e817aa91aac9/ScreeningPhaseStability/ScreeningPhaseStability.ipynb

**Review by richardotis — APPROVED** [review]

**Comment by richardotis** [comment]
The `transpose` operation after `where` is unexpected. What's the explanation?

**Comment by bocklund** [comment]
It seems like when you index the coordinate `eq_result.X_ZN` of `eq_result.X_ZN.where(mask_cond)`, xarray puts the dimension corresponding to the coordinate into the first dimension and then appends the unique dimensions of `mask_cond` (`N`, `P`, `T` in this case). The same thing happens for `eq_result.T.where(mask_cond)`, so the dimensions after masking become `(X_ZN, N, P, T)` and `(T, N, P, X_N)` for `eq_result.X_ZN` and `eq_result.T`, respectively. In this case, that means the shapes become `(50, 1, 1, 70)` and `(70, 1, 1, 50)`, which are mis-aligned. The call to `transpose` resets the coordinates to be in the same order, the same as in `mask_cond`.

**Pull request merged**
